### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by diasdavid**
We created a logo to help the clarify the difference between js-ipfs and js-ipfs-api. Would you like to add to your client library as well? You can see how it looks here: https://github.com/ipfs/js-ipfs-api

This design is from @akrych 🌟

### CODE REVIEW

**Comment by NeoTeo** [comment]
Sorry @diasdavid For some reason I wasn't notified of your pull request. 
Looks really good :)

**Comment by diasdavid** [comment]
Thanks @NeoTeo :)

**Comment by NeoTeo** [comment]
Hi @diasdavid @whyrusleeping . I woke up this morning to a message saying I'd been removed from the IPFS and Multiformats organizations that I'm contributing the swift-ipfs-api and swift multihash/multiaddr to. Mistake?

:) Teo

**Comment by diasdavid** [comment]
Hi @NeoTeo, I just received a message from @lgierth notifying that he enabled 2FA in the remaining IPFS orgs and it seems that as a collateral, some of our users got removed from the org, I'm sorry for this inconvenience.

Would you mind enabling 2FA for your account? I'll add you back right away.

Please more about why enabling 2FA and comments from other users here https://github.com/ipfs/community/issues/263

**Comment by NeoTeo** [comment]
@diasdavid Thanks :) It's all enabled now.

**Comment by diasdavid** [comment]
@NeoTeo Created a Swift Team on IPFS and added you + added you back to the Swift Team in multiformats. Thank you for your patience :)

**Comment by NeoTeo** [comment]
@diasdavid NP. Thanks for your help :)

**Pull request merged**
